---
- hosts: localhost
  tasks:
    - name: Check if user exist
      with_items:
        - akourdi
        - otorio
      ignore_errors: yes
      changed_when: false
      command: grep {{ item }} -q /etc/passwd

    - name: Disk usage from command module
      command: df -h
      register: space
    - debug:
            var: space

    - name: checking service status
      command: service "{{ item }}" status
      with_items:
      - docker
      register: result
      ignore_errors: yes
    - name: show serivces status report
      debug:
       var: result

    - name: Showing  Disk usage
      command: df -h
      register: space
    - debug:
            var: space

    - name: Print fstab if it was changed in last day
      find:
        paths: /etc/
        age: 1d
        patterns: 'fstab'
      register: files
    - debug:
            var: files
