---
- hosts: localhost
  tasks:
    - name: Check for user
      with_items:
        - otorio
      ignore_errors: yes
      changed_when: false
      command: grep {{ item }} -q /etc/passwd

    - name: Disk usage from command module
      command: df -h
      register: space
    - debug:
            var: space

    - name: checking service status
      command: systemctl status "{{ item }}"
      with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      register: result
      ignore_errors: yes
    - name: show serivces status report
      debug:
       var: result

    - name: Showing  Disk usage
      command: df -h
      register: space
    - debug:
            var: space

    - name: Recursively find /tmp files older than 2 days
      find:
        paths: /tmp
        age: 2d
        recurse: yes
