---
- name: Clean apt
  become: true
  shell: apt clean all
  tags: [common]

- name: upgrade all packages
  become: true
  apt: name=*
  tags: [common]

- name: install unzip
  become: true
  apt: name=unzip
  tags: [common]

- name: Install python setup tools
  become: true
  apt: name=python-setuptools
  tags: [common]

- name: Install Pypi
  become: true
  apt: name=pip
  tags: [common]

- name: install git
  become: true
  apt: name=git
  tags: [common]
