---
- name: Install docker-py
  become: true
  pip:
    name: 
       - docker-py
  tags: [docker]
 

- name: Update docker repo
  become: true
  lineinfile:
    dest: /etc/yum.repos.d/docker.repo
    create: yes
    line: "{{ item }}"
  with_items:
    - "[dockerrepo]"
    - "name=Docker Repository"
    - "baseurl=https://apt.dockerproject.org/repo/main/centos/7/"
    - "enabled=1"
    - "gpgcheck=1"
    - "gpgkey=https://apt.dockerproject.org/gpg"
  tags: [docker]

- name: Install Docker
  become: true
  apt: pkg=docker-engine state=present
  tags: [docker]

- name: enable sysv dockerd service
  become: true
  service:
    name: docker
    enabled: yes
  tags: [docker]

- name: Start service
  become: true
  service:
    name: docker
    state: started
  tags: [docker]
